version: '2'


services:
    web:
      restart: always
      build:
        context: .
      command: >
        bash -c "python3 manage.py migrate
        && python3 manage.py loaddata fixtures/categories.json
        && python3 manage.py runserver 0.0.0.0:8000"
      ports:
       - '8000:8000'
      depends_on:
       - db
      volumes:
       - .:/code
      environment:
       - DJANGO_SETTINGS_MODULE=ajax_web_news.settings.prod
      networks:
       - main

    db:
      image: postgres
      volumes:
       - ./.postgres-data:/var/lib/postgresql/data
      networks:
        - main

networks:
  main:
